/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author boubadiop
 */
public class Authentification extends javax.swing.JFrame {
    //declaration
    Connection conn = null;
    PreparedStatement prepared = null;
    ResultSet resultat = null;
    ConnectionDB myConnexion = new ConnectionDB();
    

    /**
     * Creates new form Authentification
     */
    public Authentification() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        labelpassword = new javax.swing.JLabel();
        btnconnexion = new javax.swing.JButton();
        inputpassword = new javax.swing.JPasswordField();
        inputusername = new javax.swing.JTextField();
        labelusername = new javax.swing.JLabel();
        btnFermer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 36, -1, -1));

        jPanel5.setBackground(new java.awt.Color(45, 81, 81));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelpassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelpassword.setText("Mot de passe");
        jPanel5.add(labelpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        btnconnexion.setBackground(new java.awt.Color(45, 81, 81));
        btnconnexion.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnconnexion.setText("Se Connecter");
        btnconnexion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconnexionActionPerformed(evt);
            }
        });
        jPanel5.add(btnconnexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 314, 53));
        jPanel5.add(inputpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 328, 41));
        jPanel5.add(inputusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 328, 44));

        labelusername.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelusername.setText("Nom d'utilisateur");
        jPanel5.add(labelusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        btnFermer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnFermer.setText("Fermer");
        btnFermer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });
        jPanel5.add(btnFermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 595, 117, 47));

        jPanel1.setBackground(new java.awt.Color(144, 191, 188));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel10.setText("Authentification");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(jLabel10)
                .addContainerGap(398, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18))
        );

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 80));

        jPanel2.setBackground(new java.awt.Color(144, 191, 188));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 40, 570));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 1090, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconnexionActionPerformed
       
        // TODO add your handling code here:
        Connexion();
    }//GEN-LAST:event_btnconnexionActionPerformed

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnFermerActionPerformed

    public void Connexion(){
//         String labelusername = inputusername.getText().toString();
//       String labelpassword = inputpassword.getText().toString();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionecole","root","root");
            String sql = "Select * from admin where username=? and password=?";
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setString(1,inputusername.getText());
            pstm.setString(2,inputpassword.getText());
            ResultSet rs = pstm.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"Connexion établit avec succès");
                Dashboard dashboard = new Dashboard();
                dashboard.setVisible(true);
                setVisible(false);
                
            }else{
                JOptionPane.showMessageDialog(null,"Nom d'utilisateur ou mot de passe incorrect");
                inputusername.setText("");
                inputpassword.setText("");
            }
            
            conn.close();

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        
            
 

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFermer;
    private javax.swing.JButton btnconnexion;
    private javax.swing.JPasswordField inputpassword;
    private javax.swing.JTextField inputusername;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelpassword;
    private javax.swing.JLabel labelusername;
    // End of variables declaration//GEN-END:variables
}
