/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagement;

import java.awt.event.ItemListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import schoolmanagement.ConnectionDB;

/**
 *
 * @author boubadiop
 */
public class GestionEtudiant extends javax.swing.JFrame {

    /**
     * Creates new form GestionEtudiant
     */
    
    Statement stmt;
    ResultSet Rs;
    DefaultTableModel model = new DefaultTableModel();
    ConnectionDB myconnexion = new ConnectionDB();
    
    
    
    public GestionEtudiant() {
        initComponents();
        comboGoupe();
        model.addColumn("id");
        model.addColumn("Matricule");
        model.addColumn("Nom");
        model.addColumn("Prenom");
        model.addColumn("Date Naissance");
        model.addColumn("Lieu Naissance");
        model.addColumn("Adresse");
        model.addColumn("Tel");
        model.addColumn("Email");
        model.addColumn("Nationalite");
        model.addColumn("Genre");
        model.addColumn("Groupe Sanguin");
        model.addColumn("Groupe");
        
        try{
            stmt = myconnexion.obtenirCon().createStatement();
            ResultSet Rs = stmt.executeQuery("select * from etudiant");
            while(Rs.next()){
            model.addRow(new Object[]{Rs.getString("id"),Rs.getString("matricule"),Rs.getString("nom"),Rs.getString("prenom"),Rs.getString("dateNaissance"),Rs.getString("lieuNaissance"),Rs.getString("adresse"),Rs.getString("telephone"),Rs.getString("email"),Rs.getString("nationalite"),Rs.getString("genre"),Rs.getString("groupeSanguin"),Rs.getString("Groupe")});
            }
        }catch(Exception e){
            System.out.println(e);
            
        }
        


     table.setModel(model);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelPrenom = new javax.swing.JLabel();
        labelMatri = new javax.swing.JLabel();
        labelDateNai = new javax.swing.JLabel();
        labelLieuNaiss = new javax.swing.JLabel();
        labelAdresse = new javax.swing.JLabel();
        labelTel = new javax.swing.JLabel();
        labelMail = new javax.swing.JLabel();
        labelNationalite = new javax.swing.JLabel();
        labelGenre = new javax.swing.JLabel();
        labelGroupSang = new javax.swing.JLabel();
        inputNom = new javax.swing.JTextField();
        inputPrenom = new javax.swing.JTextField();
        inputMatricule = new javax.swing.JTextField();
        inputDateNaissance = new javax.swing.JTextField();
        inputLieuNaissance = new javax.swing.JTextField();
        inputAdresse = new javax.swing.JTextField();
        inputTel = new javax.swing.JTextField();
        inputMail = new javax.swing.JTextField();
        inputNationalite = new javax.swing.JTextField();
        inputGenre = new javax.swing.JTextField();
        inputGroupeSanguin = new javax.swing.JTextField();
        buttonSupprimerEtudiant = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        inputSearchNom = new javax.swing.JTextField();
        labelSearchNom = new javax.swing.JLabel();
        ButtonSearch = new javax.swing.JButton();
        buttonAjouterEtudiant = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        buttonModifEtudiant = new javax.swing.JButton();
        labelID = new javax.swing.JLabel();
        inputID = new javax.swing.JTextField();
        btnQuitter = new javax.swing.JButton();
        labelGroupe = new javax.swing.JLabel();
        jCombogroupe = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 1233, -1, -1));

        jPanel4.setBackground(new java.awt.Color(45, 81, 81));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Gestion Etudiant");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 338, -1));

        labelName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelName.setText("Nom");
        jPanel4.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 73, -1));

        labelPrenom.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelPrenom.setText("Prenom");
        jPanel4.add(labelPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        labelMatri.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelMatri.setText("Matricule");
        jPanel4.add(labelMatri, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        labelDateNai.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelDateNai.setText("Date Naissance");
        jPanel4.add(labelDateNai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        labelLieuNaiss.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelLieuNaiss.setText("Lieu Naissance");
        jPanel4.add(labelLieuNaiss, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        labelAdresse.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelAdresse.setText("Adresse");
        jPanel4.add(labelAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        labelTel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelTel.setText("Téléphone ");
        jPanel4.add(labelTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        labelMail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelMail.setText("Email");
        jPanel4.add(labelMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        labelNationalite.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelNationalite.setText("Nationalité");
        jPanel4.add(labelNationalite, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        labelGenre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelGenre.setText("Genre");
        jPanel4.add(labelGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, -1, -1));

        labelGroupSang.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelGroupSang.setText("Groupe Sanguin");
        jPanel4.add(labelGroupSang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 750, -1, -1));

        inputNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomActionPerformed(evt);
            }
        });
        jPanel4.add(inputNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 308, 47));

        inputPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPrenomActionPerformed(evt);
            }
        });
        jPanel4.add(inputPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 308, 49));
        jPanel4.add(inputMatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 308, 47));
        jPanel4.add(inputDateNaissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 308, 47));
        jPanel4.add(inputLieuNaissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 308, 47));
        jPanel4.add(inputAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 308, 47));
        jPanel4.add(inputTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 308, 47));
        jPanel4.add(inputMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 308, 50));

        inputNationalite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNationaliteActionPerformed(evt);
            }
        });
        jPanel4.add(inputNationalite, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 630, 308, 42));

        inputGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGenreActionPerformed(evt);
            }
        });
        jPanel4.add(inputGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 680, 308, 49));

        inputGroupeSanguin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGroupeSanguinActionPerformed(evt);
            }
        });
        jPanel4.add(inputGroupeSanguin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 740, 308, 47));

        buttonSupprimerEtudiant.setBackground(new java.awt.Color(45, 81, 81));
        buttonSupprimerEtudiant.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonSupprimerEtudiant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagement/images/icons8-supprimer-50.png"))); // NOI18N
        buttonSupprimerEtudiant.setText("Supprimer");
        buttonSupprimerEtudiant.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonSupprimerEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupprimerEtudiantActionPerformed(evt);
            }
        });
        jPanel4.add(buttonSupprimerEtudiant, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 560, 190, 60));

        table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        table.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Matricule", "Nom", "Prenom", "Date Naissance", "Lieu Naissance", "Adresse", "Tel", "Email", "Nationalite", "Genre", "Groupe Sanguin", "Groupe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 245, 830, 260));
        jPanel4.add(inputSearchNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(851, 190, 214, 39));

        labelSearchNom.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelSearchNom.setText("Donner le nom");
        jPanel4.add(labelSearchNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 189, 136, 40));

        ButtonSearch.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ButtonSearch.setText("Rechercher");
        ButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSearchActionPerformed(evt);
            }
        });
        jPanel4.add(ButtonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1077, 191, 162, 39));

        buttonAjouterEtudiant.setBackground(new java.awt.Color(45, 81, 81));
        buttonAjouterEtudiant.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonAjouterEtudiant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagement/images/icons8-ajouter-un-utilisateur-homme-50.png"))); // NOI18N
        buttonAjouterEtudiant.setText("Ajouter");
        buttonAjouterEtudiant.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonAjouterEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjouterEtudiantActionPerformed(evt);
            }
        });
        jPanel4.add(buttonAjouterEtudiant, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, 181, 65));

        jButton1.setBackground(new java.awt.Color(45, 81, 81));
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Actualiser");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 100, 168, 51));

        buttonModifEtudiant.setBackground(new java.awt.Color(45, 81, 81));
        buttonModifEtudiant.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonModifEtudiant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagement/images/icons8-modifier-utilisateur-50.png"))); // NOI18N
        buttonModifEtudiant.setText("Modifier");
        buttonModifEtudiant.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonModifEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifEtudiantActionPerformed(evt);
            }
        });
        jPanel4.add(buttonModifEtudiant, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, 190, 65));

        labelID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelID.setText("ID");
        jPanel4.add(labelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 81, 28));
        jPanel4.add(inputID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 308, 47));

        btnQuitter.setBackground(new java.awt.Color(45, 81, 81));
        btnQuitter.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagement/images/icons8-déconnexion-50.png"))); // NOI18N
        btnQuitter.setText("Quitter");
        btnQuitter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });
        jPanel4.add(btnQuitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 560, 190, 60));

        labelGroupe.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelGroupe.setText("Groupe");
        jPanel4.add(labelGroupe, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 710, -1, -1));

        jCombogroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombogroupeActionPerformed(evt);
            }
        });
        jPanel4.add(jCombogroupe, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 700, 308, 50));

        jPanel2.setBackground(new java.awt.Color(144, 191, 188));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 30));

        jPanel3.setBackground(new java.awt.Color(144, 191, 188));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 970, 950, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void deplace(int i){
        try{
            inputID.setText(model.getValueAt(i,0).toString());
            inputMatricule.setText(model.getValueAt(i,1).toString());
            inputNom.setText(model.getValueAt(i,2).toString());
            inputPrenom.setText(model.getValueAt(i,3).toString());
            inputDateNaissance.setText(model.getValueAt(i,4).toString());
            inputLieuNaissance.setText(model.getValueAt(i,5).toString());
            inputAdresse.setText(model.getValueAt(i,6).toString());
            inputTel.setText(model.getValueAt(i,7).toString());
            inputMail.setText(model.getValueAt(i,8).toString());
            inputGenre.setText(model.getValueAt(i,9).toString());
            inputNationalite.setText(model.getValueAt(i,10).toString());
            inputGroupeSanguin.setText(model.getValueAt(i,11).toString());
            jCombogroupe.setSelectedItem(model.getValueAt(1,12).toString());
        }catch(Exception e){
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "erreur de deplacement"+e.getMessage());
        }
    }
    private void buttonModifEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifEtudiantActionPerformed
        // TODO add your handling code here:
        modifierEtudiant();
        comboGoupe();

    }//GEN-LAST:event_buttonModifEtudiantActionPerformed

    private void buttonAjouterEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjouterEtudiantActionPerformed
        // TODO add your handling code here:
        ajouterEtudiant();
//        comboGoupe();

        
    }//GEN-LAST:event_buttonAjouterEtudiantActionPerformed

    private void buttonSupprimerEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupprimerEtudiantActionPerformed
        // TODO add your handling code here:
        supprimerEtudiant();
        actualiser();
        
       
    }//GEN-LAST:event_buttonSupprimerEtudiantActionPerformed

    private void inputGroupeSanguinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGroupeSanguinActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_inputGroupeSanguinActionPerformed

    private void inputNationaliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNationaliteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNationaliteActionPerformed

    private void inputNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomActionPerformed

    private void inputGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGenreActionPerformed

    private void inputPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPrenomActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        try{
          int i = table.getSelectedRow();
            deplace(i);  
        }catch(Exception e){
            
          JOptionPane.showMessageDialog(null, "erreur de deplacement"+e.getLocalizedMessage());
        }
    }//GEN-LAST:event_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        actualiser();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSearchActionPerformed
        // TODO add your handling code here:
        
        try{
            model.setRowCount(0);//pour vider la liste des etudiants
            Rs =stmt.executeQuery("Select * From etudiant WHERE nom ='"+inputSearchNom.getText()+"' ");
            while(Rs.next()){
                Object [] etudiant ={Rs.getInt(1),Rs.getString(2),Rs.getString(3),Rs.getString(4),Rs.getString(5),Rs.getString(6),
                Rs.getString(7),Rs.getString(8),Rs.getString(9),Rs.getString(10),Rs.getString(11),Rs.getString(12),Rs.getString(13)};
                model.addRow(etudiant);
            }
            if(model.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "Il n'y a aucun ètudiant");
            }else{
                int i=0;
                deplace(i);
            }
        }catch(Exception e){
            System.err.println(e);
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_ButtonSearchActionPerformed

    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
        // TODO add your handling code here:
        dispose();
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
    }//GEN-LAST:event_btnQuitterActionPerformed

    private void jCombogroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombogroupeActionPerformed
        // TODO add your handling code here:
//        comboGoupe();
    }//GEN-LAST:event_jCombogroupeActionPerformed

    //Recuperation des informations
    
    public void ajouterEtudiant(){
        String labelID = inputID.getText();
        String labelMatricule = inputMatricule.getText();
        String labelName = inputNom.getText();
        String labelPrenom = inputPrenom.getText();
        String labelDateNai = inputDateNaissance.getText();
        String labelLieuNai = inputLieuNaissance.getText();
        String labelAdresse = inputAdresse.getText();
        String labelTel = inputTel.getText();
        String labelMail = inputMail.getText();
        String labelNationalite = inputNationalite.getText();
        String labelGenre = inputGenre.getText();
        String labelGroupSang = inputGroupeSanguin.getText();
        String labelGroupe = jCombogroupe.getSelectedItem().toString();
        String reqAjoutEtudiant = "INSERT INTO etudiant(id,matricule,nom,prenom,dateNaissance,lieuNaissance,adresse,telephone,email,nationalite,genre,groupeSanguin,groupe) VALUES('"+labelID+"','"+labelMatricule+"','"+labelName+"','"+labelPrenom+"','"+labelDateNai+"','"+labelLieuNai+"','"+labelAdresse+"','"+labelTel+"','"+labelMail+"','"+labelNationalite+"','"+labelGenre+"','"+labelGroupSang+"','"+labelGroupe+"')";  
       
       inputID.setText("");
       inputMatricule.setText("");
       inputNom.setText("");
       inputPrenom.setText("");
       inputDateNaissance.setText("");
       inputLieuNaissance.setText("");
       inputAdresse.setText("");
       inputTel.setText("");
       inputMail.setText("");
       inputNationalite.setText("");
       inputGenre.setText("");
       inputGroupeSanguin.setText("");
       jCombogroupe.setSelectedItem("");
       
       try{
           stmt = myconnexion.obtenirCon().createStatement();
           stmt.executeUpdate(reqAjoutEtudiant);
           JOptionPane.showMessageDialog(null,"Etudiant ajouté avec succès");

       }catch(SQLException e){
           System.out.println(e);
           
       }

      
        
    }
    
    public void modifierEtudiant(){
       try{
           if(JOptionPane.showConfirmDialog(null, "Confirmer la modification","modification",
                   JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
               stmt.executeUpdate("UPDATE etudiant SET matricule='"+inputMatricule.getText()+"',nom='"+inputNom.getText()+"',prenom='"+inputPrenom.getText()+
                       "',dateNaissance='"+inputDateNaissance.getText()+"',lieuNaissance='"+inputLieuNaissance.getText()+
                       "',adresse='"+inputAdresse.getText()+"', telephone='"+inputTel.getText()+"', email='"+inputMail.getText()+
                       "', nationalite='"+inputNationalite.getText()+"',genre='"+inputGenre.getText()+"', groupeSanguin='"+inputGroupeSanguin.getText()+"',groupe='"+jCombogroupe.getSelectedItem().toString()+
                       "' WHERE id="+inputID.getText());
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Modificataion invalide"+e.getMessage());
           System.err.println(e);
       }
        

    }
    
    public void supprimerEtudiant(){
        try{
           if(JOptionPane.showConfirmDialog(null, "Êtes-vous sure de vouloir supprimer cet étudiant?","supprimer étudiant",
                   JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
               
           if(inputID.getText().length() != 0){
               stmt.executeUpdate("Delete From etudiant where id = "+inputID.getText());
           }else{
               JOptionPane.showMessageDialog(null, "Veuillez remplir le champ ID");
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Erreur de supression"+e.getMessage());
           System.err.println(e);
       }
        
    }
    
    public void actualiser(){
        try{
            model.setRowCount(0);
            stmt = myconnexion.obtenirCon().createStatement();
            ResultSet Rs = stmt.executeQuery("select * from etudiant");
            while(Rs.next()){
            model.addRow(new Object[]{Rs.getString("id"),Rs.getString("matricule"),Rs.getString("nom"),Rs.getString("prenom"),Rs.getString("dateNaissance"),Rs.getString("lieuNaissance"),Rs.getString("adresse"),Rs.getString("telephone"),Rs.getString("email"),Rs.getString("nationalite"),Rs.getString("genre"),Rs.getString("groupeSanguin"),Rs.getString("groupe")});
            inputID.setText("");
            inputMatricule.setText("");
            inputNom.setText("");
            inputPrenom.setText("");
            inputDateNaissance.setText("");
            inputLieuNaissance.setText("");
            inputAdresse.setText("");
            inputTel.setText("");
            inputMail.setText("");
            inputNationalite.setText("");
            inputGenre.setText("");
            inputGroupeSanguin.setText("");
            jCombogroupe.setSelectedItem("");
            

            }
        }catch(Exception e){
            System.out.println(e);
            
        }
        table.setModel(model);
    }
    
    private void comboGoupe(){
       try{
            stmt = myconnexion.obtenirCon().createStatement();
            ResultSet Rs = stmt.executeQuery("select * from groupe");
            while(Rs.next()){
                jCombogroupe.addItem(Rs.getString("nomGroupe"));
            }
        }catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
            
        }
        
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionEtudiant().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSearch;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JButton buttonAjouterEtudiant;
    private javax.swing.JButton buttonModifEtudiant;
    private javax.swing.JButton buttonSupprimerEtudiant;
    private javax.swing.JTextField inputAdresse;
    private javax.swing.JTextField inputDateNaissance;
    private javax.swing.JTextField inputGenre;
    private javax.swing.JTextField inputGroupeSanguin;
    private javax.swing.JTextField inputID;
    private javax.swing.JTextField inputLieuNaissance;
    private javax.swing.JTextField inputMail;
    private javax.swing.JTextField inputMatricule;
    private javax.swing.JTextField inputNationalite;
    private javax.swing.JTextField inputNom;
    private javax.swing.JTextField inputPrenom;
    private javax.swing.JTextField inputSearchNom;
    private javax.swing.JTextField inputTel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCombogroupe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAdresse;
    private javax.swing.JLabel labelDateNai;
    private javax.swing.JLabel labelGenre;
    private javax.swing.JLabel labelGroupSang;
    private javax.swing.JLabel labelGroupe;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelLieuNaiss;
    private javax.swing.JLabel labelMail;
    private javax.swing.JLabel labelMatri;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNationalite;
    private javax.swing.JLabel labelPrenom;
    private javax.swing.JLabel labelSearchNom;
    private javax.swing.JLabel labelTel;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
