/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagement;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author boubadiop
 */
public class GestionGroupe extends javax.swing.JFrame {
    Statement stmt;
    ResultSet Rs;
    DefaultTableModel model = new DefaultTableModel();
    ConnectionDB myconnexion = new ConnectionDB();

    /**
     * Creates new form GestionGroupe
     */
    public GestionGroupe() {
        initComponents();
        
         model.addColumn("ID");
        model.addColumn("Nom Groupe");
        model.addColumn("Date Creation");
        
        
        try{
            stmt = myconnexion.obtenirCon().createStatement();
            ResultSet Rs = stmt.executeQuery("select * from groupe");
            while(Rs.next()){
            model.addRow(new Object[]{Rs.getString("id"),Rs.getString("nomGroupe"),Rs.getString("dateCreation")});
            }
        }catch(Exception e){
            System.out.println(e);
            
        }
        table.setModel(model);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelNomGroupe = new javax.swing.JLabel();
        labelDateCreation = new javax.swing.JLabel();
        inputNomGroupe = new javax.swing.JTextField();
        inputDateCreation = new javax.swing.JTextField();
        btnAjoutGroupe = new javax.swing.JButton();
        btnSuppGroupe = new javax.swing.JButton();
        btnModifGroupe = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        inputSearchNomG = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        inputID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnQuitter = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelID = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 81, 81));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Gestion Groupe");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 28, 295, -1));

        labelNomGroupe.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelNomGroupe.setText("Nom Groupe");
        jPanel1.add(labelNomGroupe, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 197, -1));

        labelDateCreation.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelDateCreation.setText("Date Création du groupe");
        jPanel1.add(labelDateCreation, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));
        jPanel1.add(inputNomGroupe, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 234, 259, 38));
        jPanel1.add(inputDateCreation, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 312, 259, 36));

        btnAjoutGroupe.setBackground(new java.awt.Color(45, 81, 81));
        btnAjoutGroupe.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAjoutGroupe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagement/images/icons8-ajouter-un-groupe-d'utilisateurs-femme-femme-50.png"))); // NOI18N
        btnAjoutGroupe.setText("Creer un Groupe");
        btnAjoutGroupe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAjoutGroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutGroupeActionPerformed(evt);
            }
        });
        jPanel1.add(btnAjoutGroupe, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 478, 197, 60));

        btnSuppGroupe.setBackground(new java.awt.Color(45, 81, 81));
        btnSuppGroupe.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSuppGroupe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagement/images/icons8-supprimer-50.png"))); // NOI18N
        btnSuppGroupe.setText("Supprimer");
        btnSuppGroupe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSuppGroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppGroupeActionPerformed(evt);
            }
        });
        jPanel1.add(btnSuppGroupe, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 200, 61));

        btnModifGroupe.setBackground(new java.awt.Color(45, 81, 81));
        btnModifGroupe.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnModifGroupe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagement/images/icons8-modifier-50.png"))); // NOI18N
        btnModifGroupe.setText("Modifier Groupe");
        btnModifGroupe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModifGroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifGroupeActionPerformed(evt);
            }
        });
        jPanel1.add(btnModifGroupe, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 210, 61));

        table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom Groupe", "Date Creation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 240, 501, 176));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Donner le nom du groupe");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 194, -1, -1));
        jPanel1.add(inputSearchNomG, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 184, 181, 37));

        btnSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSearch.setText("Rechercher");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1181, 185, -1, 37));
        jPanel1.add(inputID, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 167, 259, 40));

        jButton1.setBackground(new java.awt.Color(45, 81, 81));
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Actualiser");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1141, 59, 158, 65));

        btnQuitter.setBackground(new java.awt.Color(45, 81, 81));
        btnQuitter.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagement/images/icons8-déconnexion-50.png"))); // NOI18N
        btnQuitter.setText("Quittter");
        btnQuitter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 200, 60));

        jPanel2.setBackground(new java.awt.Color(144, 191, 188));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 20));

        labelID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelID.setText("ID");
        jPanel1.add(labelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 105, 38));

        jPanel3.setBackground(new java.awt.Color(144, 191, 188));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1270, 30));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void deplace(int i){
        try{
            inputID.setText(model.getValueAt(i,0).toString());
            inputNomGroupe.setText(model.getValueAt(i,1).toString());
            inputDateCreation.setText(model.getValueAt(i,2).toString());
            
        }catch(Exception e){
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "erreur de deplacement"+e.getMessage());
        }
    }
    private void btnAjoutGroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutGroupeActionPerformed
        // TODO add your handling code here:
        ajoutGroupe();
    }//GEN-LAST:event_btnAjoutGroupeActionPerformed

    private void btnModifGroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifGroupeActionPerformed
        // TODO add your handling code here:
        modifGroupe();
    }//GEN-LAST:event_btnModifGroupeActionPerformed

    private void btnSuppGroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppGroupeActionPerformed
        // TODO add your handling code here:
        suppGroupe();
        actualiser();
    }//GEN-LAST:event_btnSuppGroupeActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        try{
          int i = table.getSelectedRow();
            deplace(i);  
        }catch(Exception e){
            
          JOptionPane.showMessageDialog(null, "erreur de deplacement"+e.getLocalizedMessage());
        }
    }//GEN-LAST:event_tableMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try{
            model.setRowCount(0);//pour vider la liste des groupes
            Rs =stmt.executeQuery("Select * From groupe WHERE nomGroupe ='"+inputSearchNomG.getText()+"' ");
            while(Rs.next()){
                Object [] groupe ={Rs.getInt(1),Rs.getString(2),Rs.getString(3)};
                model.addRow(groupe);
            }
            if(model.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "Il n'y a aucun groupe");
            }else{
                int i=0;
                deplace(i);
            }
        }catch(Exception e){
            System.err.println(e);
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        actualiser();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
        // TODO add your handling code here:
        dispose();
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
    }//GEN-LAST:event_btnQuitterActionPerformed
    
    public void ajoutGroupe(){
        String labelID = inputID.getText();
        String labelNomGroupe = inputNomGroupe.getText();
        String labelDateCreation = inputDateCreation.getText();
       
        
        
       String reqAjoutEtudiant = "INSERT INTO groupe(id,nomGroupe,dateCreation) VALUES('"+labelID+"','"+labelNomGroupe+"','"+labelDateCreation+"')";  
       inputID.setText("");
       inputNomGroupe.setText("");
       inputDateCreation.setText("");
       
       
       try{
           stmt = myconnexion.obtenirCon().createStatement();
           stmt.executeUpdate(reqAjoutEtudiant);
           JOptionPane.showMessageDialog(null,"Groupe Crée avec succès");

       }catch(SQLException e){
           System.out.println(e);
       }
    }
    
    public void modifGroupe(){
        try{
           if(JOptionPane.showConfirmDialog(null, "Confirmer la modification","modification",
                   JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
               stmt.executeUpdate("UPDATE groupe SET nomGroupe='"+inputNomGroupe.getText()+"',dateCreation='"+inputDateCreation.getText()+
                       "' WHERE id="+inputID.getText());
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Modificataion invalide"+e.getMessage());
           System.err.println(e);
       }
    }
    
    public void suppGroupe(){
        try{
           if(JOptionPane.showConfirmDialog(null, "Êtes-vous sure de vouloir supprimer ce groupe?","supprimer groupe",
                   JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
               
           if(inputID.getText().length() != 0){
               stmt.executeUpdate("Delete From groupe where id = "+inputID.getText());
           }else{
               JOptionPane.showMessageDialog(null, "Veuillez remplir le champ ID");
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Erreur de supression"+e.getMessage());
           System.err.println(e);
       }
    }
    
    private void actualiser(){
        try{
            model.setRowCount(0);
            stmt = myconnexion.obtenirCon().createStatement();
            ResultSet Rs = stmt.executeQuery("select * from groupe");
            while(Rs.next()){
            model.addRow(new Object[]{Rs.getString("id"),Rs.getString("nomGroupe"),Rs.getString("dateCreation")});
            inputID.setText("");
            inputNomGroupe.setText("");
            inputDateCreation.setText("");
                        
            
            

            }
        }catch(Exception e){
            System.out.println(e);
            
        }
        table.setModel(model);

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionGroupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionGroupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionGroupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionGroupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionGroupe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjoutGroupe;
    private javax.swing.JButton btnModifGroupe;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSuppGroupe;
    private javax.swing.JTextField inputDateCreation;
    private javax.swing.JTextField inputID;
    private javax.swing.JTextField inputNomGroupe;
    private javax.swing.JTextField inputSearchNomG;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDateCreation;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNomGroupe;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
